import { AUTHORING_AGREED_STORYBOARD_CSS } from './agreed-storyboard';
import { AUTHORING_AGREED_PLACEMENT_CSS } from './agreed-placement';
import { AUTHORING_AGREED_POPUP_APPEARANCE_CSS } from './agreed-popup-appearance';
import { AUTHORING_AGREED_PRESENTATION_CSS } from './agreed-presentation';
import { AUTHORING_AGREED_ACTION_WORKBENCH_CSS } from './agreed-action-workbench';
import { AUTHORING_AGREED_CONTENT_PROPERTIES_CSS } from './agreed-content-properties';
import { AUTHORING_AGREED_BRANCHING_CSS } from './agreed-branching';
import { AUTHORING_AGREED_BATCH_FLOW_CSS } from './agreed-batch-flow';
import { AUTHORING_AGREED_REVIEW_CSS } from './agreed-review';
import { AUTHORING_AGREED_FLOW_CANVAS_CSS } from './agreed-flow-canvas';
import { AUTHORING_AGREED_FLOW_WORKBENCH_CSS } from './agreed-flow-workbench';
import { AUTHORING_AGREED_RESPONSIVE_CSS } from './agreed-responsive';

export const AUTHORING_AGREED_MODES_CSS = `
  ${AUTHORING_AGREED_STORYBOARD_CSS}
  ${AUTHORING_AGREED_PLACEMENT_CSS}
  ${AUTHORING_AGREED_POPUP_APPEARANCE_CSS}
  ${AUTHORING_AGREED_PRESENTATION_CSS}
  ${AUTHORING_AGREED_ACTION_WORKBENCH_CSS}
  ${AUTHORING_AGREED_CONTENT_PROPERTIES_CSS}
  ${AUTHORING_AGREED_BRANCHING_CSS}
  ${AUTHORING_AGREED_BATCH_FLOW_CSS}
  ${AUTHORING_AGREED_REVIEW_CSS}
  ${AUTHORING_AGREED_FLOW_CANVAS_CSS}
  ${AUTHORING_AGREED_FLOW_WORKBENCH_CSS}
  ${AUTHORING_AGREED_RESPONSIVE_CSS}
`;
