import type { ProductCapabilityId } from './product-capabilities';

export const IMPLEMENTED_PRODUCT_CAPABILITY_IDS = [
  'authoring.spotlight-motion',
  'authoring.target-styling',
  'runtime.target-focus',
  'runtime.motion-presets',
  'authoring.narrated-autoplay',
  'authoring.shareable-demo-links',
  'authoring.voice-driven',
  'authoring.record-to-author',
  'authoring.transient-state-targets',
  'authoring.data-relative-targets',
  'authoring.multi-app-journeys',
  'authoring.storyboard',
  'authoring.templates',
  'authoring.side-by-side',
  'authoring.version-diff',
  'authoring.change-aware-copy',
  'delivery.adaptive',
  'delivery.ab-testing',
  'analytics.scoped-replay',
  'runtime.block-conditions',
  'collaboration.comment-threads',
  'commercial.entitlements',
  'commercial.metering',
  'delivery.scheduling',
  'delivery.audience-rules',
  'delivery.event-triggers',
  'delivery.lifecycle-triggers',
  'runtime.experience-parity',
  'analytics.completion',
  'analytics.forms',
  'analytics.funnels',
  'analytics.adoption',
  'analytics.retention',
  'analytics.segmentation',
  'analytics.cohorts',
  'analytics.csv-export',
  'analytics.warehouse-sync',
  'analytics.raw-export',
  'analytics.release-history',
  'authoring.ask-lodariq',
  'authoring.translation',
  'authoring.add-locale',
  'authoring.locale-layout-qa',
  'authoring.locale-media',
  'authoring.narration-audio',
  'brand.theme-variants',
  'brand.drift-notifications',
  'governance.audit-browsing',
  'governance.change-export',
  'governance.accessibility-sweep',
  'collaboration.presence',
  'collaboration.locks',
  'governance.base-roles',
  'governance.custom-roles',
  'platform.api',
  'platform.webhooks',
  'platform.data-residency',
  'governance.scim',
  'governance.production-approval',
  'delivery.immutable-publication',
] as const satisfies readonly ProductCapabilityId[];

const IMPLEMENTED_PRODUCT_CAPABILITIES = new Set<ProductCapabilityId>(
  IMPLEMENTED_PRODUCT_CAPABILITY_IDS,
);

export function productCapabilityIsImplemented(id: ProductCapabilityId): boolean {
  return IMPLEMENTED_PRODUCT_CAPABILITIES.has(id);
}
