import type { TSchema } from '@sinclair/typebox';
import {
  ACCESSIBILITY_GOVERNANCE_REFERENCE_SCHEMAS,
  ACCESSIBILITY_GOVERNANCE_SCHEMAS,
} from './accessibility-governance';
import {
  ANALYTICS_WAREHOUSE_REFERENCE_SCHEMAS,
  ANALYTICS_WAREHOUSE_SCHEMAS,
} from './analytics-warehouse';
import {
  COMMERCIAL_BILLING_REFERENCE_SCHEMAS,
  COMMERCIAL_BILLING_SCHEMAS,
} from './commercial-billing';
import {
  GOVERNANCE_CHANGE_HISTORY_REFERENCE_SCHEMAS,
  GOVERNANCE_CHANGE_HISTORY_SCHEMAS,
} from './governance-change-history';
import { FASTIFY_REFERENCE_SCHEMA_REGISTRY, SCHEMA_REGISTRY } from './registry';

/**
 * Control-plane-only contracts stay behind this explicit subpath so browser
 * authoring does not absorb billing, warehouse, governance export, or sweep
 * schemas through the general document contract barrel.
 */
export const SERVER_SCHEMA_REGISTRY: TSchema[] = [
  ...SCHEMA_REGISTRY,
  ...COMMERCIAL_BILLING_REFERENCE_SCHEMAS,
  ...COMMERCIAL_BILLING_SCHEMAS,
  ...ANALYTICS_WAREHOUSE_REFERENCE_SCHEMAS,
  ...ANALYTICS_WAREHOUSE_SCHEMAS,
  ...GOVERNANCE_CHANGE_HISTORY_REFERENCE_SCHEMAS,
  ...GOVERNANCE_CHANGE_HISTORY_SCHEMAS,
  ...ACCESSIBILITY_GOVERNANCE_REFERENCE_SCHEMAS,
  ...ACCESSIBILITY_GOVERNANCE_SCHEMAS,
];

export const SERVER_FASTIFY_REFERENCE_SCHEMA_REGISTRY: TSchema[] = [
  ...FASTIFY_REFERENCE_SCHEMA_REGISTRY,
  ...COMMERCIAL_BILLING_REFERENCE_SCHEMAS,
  ...ANALYTICS_WAREHOUSE_REFERENCE_SCHEMAS,
  ...GOVERNANCE_CHANGE_HISTORY_REFERENCE_SCHEMAS,
  ...ACCESSIBILITY_GOVERNANCE_REFERENCE_SCHEMAS,
];
