import {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  Bell,
  Bookmark,
  Calendar,
  CalendarDays,
  Camera,
  ChartNoAxesColumn,
  Check,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  Clock,
  Copy,
  CreditCard,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  Flag,
  Gift,
  Globe,
  Heart,
  Home,
  Image,
  Info,
  KeyRound,
  Laptop,
  Laugh,
  Lightbulb,
  Link,
  LockKeyhole,
  Mail,
  MapPin,
  MessageCircle,
  Minus,
  Music,
  Package,
  PartyPopper,
  Phone,
  Play,
  Plus,
  Rocket,
  Search,
  Settings,
  Share2,
  Shield,
  ShoppingCart,
  Smile,
  Smartphone,
  Sparkles,
  Star,
  Tag,
  Target,
  ThumbsUp,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  Upload,
  User,
  Users,
  Video,
  Wrench,
  X,
  Zap,
  createElement as createLucideElement,
  type IconNode,
} from 'lucide';

const COMPOSITION_ICON_NODES: Readonly<Record<string, IconNode>> = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'badge-check': BadgeCheck,
  'calendar-days': CalendarDays,
  'chart-no-axes-column': ChartNoAxesColumn,
  'chevron-right': ChevronRight,
  'circle-check': CircleCheck,
  'circle-dollar-sign': CircleDollarSign,
  'circle-help': CircleHelp,
  'credit-card': CreditCard,
  'external-link': ExternalLink,
  'eye-off': EyeOff,
  'key-round': KeyRound,
  lightbulb: Lightbulb,
  'lock-keyhole': LockKeyhole,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'party-popper': PartyPopper,
  'share-2': Share2,
  'shopping-cart': ShoppingCart,
  'thumbs-up': ThumbsUp,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  bell: Bell,
  bookmark: Bookmark,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  clock: Clock,
  copy: Copy,
  download: Download,
  eye: Eye,
  flag: Flag,
  gift: Gift,
  globe: Globe,
  heart: Heart,
  home: Home,
  image: Image,
  info: Info,
  laptop: Laptop,
  laugh: Laugh,
  link: Link,
  lock: LockKeyhole,
  mail: Mail,
  minus: Minus,
  music: Music,
  package: Package,
  phone: Phone,
  play: Play,
  plus: Plus,
  rocket: Rocket,
  search: Search,
  settings: Settings,
  shield: Shield,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  target: Target,
  trophy: Trophy,
  truck: Truck,
  upload: Upload,
  user: User,
  users: Users,
  video: Video,
  warning: CircleAlert,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

export function createCompositionIcon(name: string): SVGElement {
  return createLucideElement(COMPOSITION_ICON_NODES[name] ?? Info);
}
