export const tenantScopedTableNames = [
  'workspaces',
  'workspace_memberships',
  'environments',
  'environment_tokens',
  'public_sdk_installations',
  'public_sdk_installation_origins',
  'public_sdk_bootstrap_grants',
  'authoring_authorization_requests',
  'authoring_activation_grants',
  'themes',
  'theme_versions',
  'style_sources',
  'product_style_applications',
  'brand_drift_runs',
  'authoring_style_recipes',
  'authoring_draft_checkpoints',
  'authoring_media_assets',
  'documents',
  'document_versions',
  'compiled_artifacts',
  'visual_check_runs',
  'publications',
  'publication_verifications',
  'release_operations',
  'release_approvals',
  'document_deployments',
  'authoring_sessions',
  'events',
  'analytics_events',
] as const;

export type TenantScopedTableName = (typeof tenantScopedTableNames)[number];
